# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declaracion',
            options={'ordering': ('estado', '-fecha', '-id')},
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 8, 21)),
        ),
    ]
