# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 23:06
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0002_auto_20190821_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracion',
            name='plantilla',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='plantilla actual', max_length=100, no_check_for_status=True),
        ),
    ]
