# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 23:23
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0003_declaracion_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion',
            name='plantilla',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='actual', max_length=100, no_check_for_status=True),
        ),
    ]
