# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0004_auto_20190821_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('archivo', models.FileField(max_length=200, upload_to=None)),
            ],
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 8, 28)),
        ),
        migrations.AlterField(
            model_name='declaracion',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaracion.Plantilla'),
        ),
    ]
