# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0005_auto_20190828_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
