# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 03:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0007_auto_20190828_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 9, 4)),
        ),
    ]
