# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-09 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0008_auto_20190904_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracion',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 9, 9)),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.TextField(),
        ),
    ]
